---
title: "Taxonomy"
output: html_document
date: "2024-10-23"
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = normalizePath("."))
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidygraph)
library(ggraph)
```


# Retreive data from docker container
```{bash eval=FALSE}
# Retrieve db.tsv from unigebsp/species_profiler image
id=$(docker create unigebsp/species_profiler)
docker cp $id:/app/db/db.tsv ./
docker rm -v $id

# Download NCBI taxonomy
wget https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump.tar.gz && mkdir -p taxdump && tar -C taxdump -zxf taxdump.tar.gz
```



```{r}
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
# Prepare Taxonomy
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
library(tidygraph)

# Load NCBI taxonomy
read_tax <- function() {
	SN <- read_tsv(file.path(genomes_dir,"taxdump/names.dmp"),col_names = c("tax_id","tax_name","name_class"),col_types="c_c___c_") |> 
		filter(name_class=="scientific name") |>
		mutate(name_class=NULL)
	N <- read_tsv(file.path(genomes_dir,"taxdump/nodes.dmp"),col_names = c("tax_id","parent","rank"),col_types="c_c_c_____________________") |>
		left_join(SN,by="tax_id",relationship="one-to-one")
	tax <- tbl_graph(N,select(N,parent,tax_id),node_key = "tax_id")
	tax
}

message("load taxonomy")
tax <- read_tax() |>
	mutate(is_db_tax = tax_id %in% ss$`Organism Taxonomic ID`) 

# Find all ancestors of selected nodes
message("find ancestors")
db_ancestors <- igraph::ego(tax,order=100,nodes=igraph::V(tax)[is_db_tax],mode="in") |> 
	map(~.x$tax_id) |>
	setNames(igraph::V(tax)[is_db_tax]$tax_id) |>
	enframe(name = "leaf_id",value = "ancestor_id") |>
	unnest(ancestor_id)


# Subset the taxonomy to selected elements and its ancestors
message("subset taxonomy to selected elements")
TAX <- tax |>
	activate(edges) |>
	filter(!edge_is_loop()) |>
	activate(nodes) |>
	mutate(is_db_ancestor = tax_id %in% db_ancestors$ancestor_id) |>
	filter(is_db_ancestor)
saveRDS(TAX,file.path(db_dir,"tax.rds"))

```



# Taxonomy
```{r}
TAX <- readRDS("tax.rds")

# Check graph topology
with_graph(TAX,graph_is_dag())
with_graph(TAX,graph_is_tree())

TAX |>
	ggraph("partition",circular=TRUE) +
	geom_node_arc_bar(aes(fill = rank), size = 0.25) +
	coord_equal()

TAX |>
	ggraph("tree",circular=TRUE) +
	geom_edge_link() +
	geom_node_point(aes(color=rank)) +
	coord_equal() +
	geom_node_label(aes(label=tax_name,fill = rank), size = 2)
```




# DB
```{r}
db <- read_tsv("db.tsv") 
g <- bind_rows(
	distinct(tibble(from=db$genus_id,to=db$species_id)),
	distinct(tibble(from=db$family_id,to=db$genus_id)),
	distinct(tibble(from=db$order_id,to=db$family_id)),
	distinct(tibble(from=db$superkingdom_id,to=db$order_id))
) |>
	filter(!is.na(from),!is.na(to)) |>
	as_tbl_graph()
```


```{r}
ggraph(g,"nicely") + 
	geom_node_point(size=3) + 
	geom_edge_link() + 
	coord_equal()

with_graph(g,graph_is_dag())
with_graph(g,graph_is_tree())

ggraph(g,"nicely") + 
	geom_node_point(size=3) + 
	geom_edge_link() + 
	coord_equal()

g |>
	ggraph("partition",circular=TRUE) + 
		geom_node_arc_bar(size = 0.25) +
		coord_equal()
```






